### ISSUE TITLE
Impressive test coverage

### ISSUE THREAD

**Issue by nobodxbodon** [ZackFra/Salesforce-Moxygen#45]
Nice to meet you and thanks for sharing the tech details in the blog!
May I ask how you prioritize which part of SOQL syntax to implement first? Based on your usage in work, how convenient to implement or both?

**Comment by ZackFra** [comment]
@nobodxbodon 

No problem, man! 

It's really simple, I first prioritized building a mechanism to mock queries by hand, i.e. by setting explicit return values. This was to ensure there's always a backup approach to allow someone to use Moxygen even if at the time a query isn't supported. 

I then prioritized common queries first and gradually built out support for more and more complex ones. What I determined as "common" was just whatever I used most at work.

**Comment by nobodxbodon** [comment]
Got it thanks. I'll use some queries in `mock-soql-database/main/default/classes/database/mock-database-tests/MockDatabaseTest.cls` when building the prototype. 
BTW are you able to use Python and `pip install` at work? Because I was planning to publish the prototype on PyPI.

**Comment by ZackFra** [comment]
@nobodxbodon 

Sorry for the delayed response, I've been a bit pre-occupied studying up for tech interviews. I can use Python, but there's already been conversations about using Moxygen at work - and unfortunately my job would likely try to claim it if I ever used it in their codebase. So it depends how dependent on Moxygen your project is.

**Comment by ZackFra** [comment]
Closing the issue due to inactivity.
